# Generated by Django 4.1.1 on 2022-11-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coinstore", name="date", field=models.DateField(auto_now=True),
        ),
    ]
